### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by ying-li-python**
### Description of your changes
This is a repository that stores default `.github/` files. Updating CODEOWNERS to `@calico/sweng-dev`

### Issue ticket number and link
[DEN-66](https://calicolabs.atlassian.net/browse/DEN-66)

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation add / update

### (If applicable) How has this been tested?

[DEN-66]: https://calicolabs.atlassian.net/browse/DEN-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ledogar** [comment]
Would this make @sweng-dev the default CODEOWNER for all future Github repo's?

**Comment by ying-li-python** [comment]
@ledogar The CODEOWNERS file helps define individuals or teams in Github repos, but the **person with admin or owner permissions of the specific Github repo** must add the individual or team with "read/write" permissions (under Settings > Collaborators and teams > Add teams), as mentioned in [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). So technically, even if the CODEOWNERS file exist in future Github repo's, the @sweng-dev does not have permissions to do anything to the code until the admin / owner of the repo explicitly updates the Github repo's settings and add the @sweng-dev team with "read/write" permissions.

**Comment by ledogar** [comment]
@ying-li-python ok I'm understanding that the CODEOWNERS would not affect the Github repo permissions, thanks for explaining.  I wanted to ask, say we merge this and then someone else in Calico outside of the sweng group creates a new repo from scratch, not using a template, etc.  Would that new repo get created with a CODEOWNERS file containing the string `@calico/sweng-dev` ?

**Comment by ying-li-python** [comment]
@ledogar Interesting, I just tried to create a new PR in the [ukbb-mri-workflows](https://github.com/calico/ukbb-mri-workflows/pull/2) repo to test out if CODEOWNERS would show up as Reviewers, with the appropriate permissions set for @calico/sweng-dev in the repo, but the CODEOWNERS file located in `.github/.github/CODEOWNERS` does not seem to affect the new repo.. I just realized that CODEOWNERS is not a support file for the `.github/` repo (as mentioned in [Supported file types](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types)

I think for now, we can remove the`.github/.github/CODEOWNERS` file, and have this repo contain only the `pull_request_template.md`

**Pull request closed without merging**
